config/routes.rb
CalendarApp::Application.routes.draw do
  root 'calendar_page#home'
  match '/event', to: 'calendar_page#event', via: 'get'

  

end

app/models/event.rb
class Event < ActiveRecord::Base
	before_save { self.name = name.downcase } 
	validates :name, presence: true, length: { maximum: 50 }
	validates :description, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calendar_page_controller.rb
class CalendarPageController < ApplicationController
  def home
  end

  def event
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_page_helper.rb
module CalendarPageHelper
end

app/views/calendar_page/event.html.erb
<h1>CalendarPage#event</h1>
<p>Find me in app/views/calendar_page/event.html.erb</p>

app/views/calendar_page/home.html.erb
<div class = "center hero-unit">
	<h1>CalendarPage#home</h1>
	<h2>
		<li><%= link_to "Create an Event", event_path %></li>
	<%= calendar @events, {:prev_text=>"<", :next_text=>">"} do |event| %>
	<div><%= link_to event.title, event %></div>
	<% end %>
</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CalendarApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>